### ISSUE TITLE
Feature Request: Make "keyfeatures" cards linkable

### ISSUE THREAD

**Issue by rossbar** [scientific-python/scientific-python-hugo-theme#69]
I think it would be a nice feature to allow the `keyfeatures` cards to link to other internal or external pages.

The hugo fresh theme has something similar: see the cards under the "Great Power Comes" section: https://hugo-fresh.vercel.app/ (though I think making the entire card clickable is preferable to adding a button; this is a minor detail though).

**Comment by stefanv** [comment]
See #72

**Comment by alphapapa** [comment]
@rossbar AFAICT this was addressed in the linked PRs, so I'm closing this issue.  Please let me know if anything remains to be done and this should be reopened, or feel free to file a new issue.  Thanks.

**Comment by rossbar** [comment]
FWIW this hasn't quite been resolved, at least in terms of anchor links for the headings.

For example - if you look at the [deployed site](https://scientific-python.org/about/) the heading titles are still not anchor links. #72 improved the situation by adding the side navbar, but I think there's still value in having the headings be anchor links (mostly for sharing links).

**Comment by alphapapa** [comment]
@stefanv @rossbar Thanks.  Assigning to myself and will investigate.
